<!-- Top content -->
<div id="home" class="parallax top-content" data-stellar-background-ratio="0.3">
    <div class="inner-bg">
        <div class="container">
            <div class="row">

                <div class="col-md-7 col-sm-7 top-description">

                    <h2 class="text-left"><strong><?=$this->domain?></strong> is te koop</h2>

                    <p>Neem contact met ons op indien u interesse heeft in dit domein. Bekijk hieronder meer van onze domeinen.</p>

                </div>


                <div class="col-md-5 col-sm-5">

                    <div class="vertical-registration-form">
                        <h3>Koop dit domein nu</h3>
                        <h6>Bent u geinteresserd in dit domein neem dan nu contact met ons op.</h6>
                        <form class="contact-form" action="<?=$this->url('contact')?>">
                            <fieldset>
                                <div class="form-group">
                                    <p>Naam</p>
                                    <input id="name" name="name" type="text" class="optin-input" required="">
                                </div>
                                <div class="form-group">
                                    <p>Email</p>
                                    <input id="email" name="email" type="email" class="optin-input" required="">
                                </div>
                                <div class="form-group">
                                    <p>Bericht</p>
                                    <textarea id="message" name="message" class="optin-input" required=""></textarea>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-top-white btn-lg" type="submit">Versturen</button>
                                </div>
                            </fieldset>

                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>