<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Koop dit domein</title>

	<!-- CSS -->
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800">
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Dosis:300,400,500,600,700">
	<link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="assets/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="assets/css/style.css">
</head>

<body data-spy="scroll" data-offset="80">

	<?=$this->content?>

	<!-- Javascript -->
	<script src="assets/js/jquery-1.10.2.min.js"></script>
	<script src="assets/bootstrap/js/bootstrap.min.js"></script>
	<script src="assets/js/retina-1.1.0.min.js"></script>
	<script src="assets/js/jquery.easing.1.3.min.js"></script>
	<script src="assets/js/jquery.stellar.min.js" type="text/javascript"></script>
	<script src="assets/js/script.js"></script>
	<script src="assets/js/parsley.min.js"></script>

</body>

</html>

